capp/__init__.py
from flask import Flask

application = Flask(__name__)

from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app
from capp.users.routes import users

application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)
application.register_blueprint(users)


capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint

carbon_app=Blueprint('carbon_app',__name__)

@carbon_app.route('/carbon_app')
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

@carbon_app.route('/carbon_app/new_entry')
def new_entry():
    return render_template('carbon_app/new_entry.html', title='new_entry')

@carbon_app.route('/carbon_app/your_data')
def your_data():
    return render_template('carbon_app/your_data.html', title='your_data')
    

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/__init__.py
#

capp/users/routes.py
from flask import render_template, Blueprint

users=Blueprint('users',__name__)

@users.route('/register')
def register():
  return render_template('users/register.html', title='register')

@users.route('/login')
def login():
  name='Mario'
  return render_template('users/login.html', title='login', name=name)

capp/templates/carbon_app/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.new_entry')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">New entry</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.your_data')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Your data</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:black; text-align: center;">Carbon App, instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:black">
                    <p style="text-align: left;">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae ratione tempore id esse nobis molestias quasi explicabo possimus ea reprehenderit.
                    </p>
                    <ol style="text-align:left;">
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                    </ol>
                    </div>
          
                    <div class="modal-footer">
                        <a href="{{url_for('carbon_app.new_entry')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">New entry</a>
                        <button class="btn btn-secondary btn-lg mr-2", style="background-color:#6c757d;" data-dismiss="modal">Close</button>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/calculator.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 
       

{% endblock content %}

capp/templates/carbon_app/new_entry.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">

    <h1>New entry:</h1>

  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/your_data.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">

    <h1>Your data:</h1>

  </div>
</section> 

        
{% endblock content %}

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_home">
  <div class="container">

    <div class="header_home">
      <div class="box"> 
        <h1 style="font-size:55px;"><span class="text-logo"> Home</span></h1>
        <p style="text-align:left;">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
        </p>
        <div class="container_buttons_links_header_home">
          <div class="btn">
              <a href="{{url_for('users.register')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Register</a>
          </div>
          <div class="btn">
              <a href="{{url_for('users.login')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Login</a>
          </div>
        </div>  
      </div>
      <div class="box">
        <img 
          src="{{url_for('static', filename='icons/carbon_app.svg')}}"
          width="325" 
          height="325"
          alt=""/>
      </div>
    </div>

  </div>
</section> 

<!-- Developers -->
<section class="section_developers">
  <div class="container">

    <div class="developers" style="display:block;">
      <h1 style="text-align:center;"> Our Team</h1>
      <p>
        Our team of economists and developers ... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut? Praesentium quidem sunt perspiciatis doloremque fugiat nesciunt quaerat ullam, pariatur iure unde ratione ipsum adipisci repellendus, repudiandae hic sit, temporibus molestias corrupti aut soluta sequi! Architecto deleniti expedita nisi repudiandae enim eum quas odit facilis placeat neque porro, animi incidunt consectetur. Maiores ab saepe tempora, iure asperiores beatae suscipit cum ipsum, rerum doloremque reprehenderit dolorum debitis, aliquam quasi. Maiores corporis fuga quasi nesciunt dolor iste, inventore necessitatibus unde!
      </p>      
    </div>

    <div class="developers">
        <div class="box">
          <img src="https://randomuser.me/api/portraits/men/10.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 1</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>
        <div class="box">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 2</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>           
        <div class="box">
          <img src="https://randomuser.me/api/portraits/men/12.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 3</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>     
    </div>

    <div class="developers">
      <div class="box2">
        <img src="https://randomuser.me/api/portraits/women/12.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Developer 4</h3>
        <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
        </div> 
      </div>
      <div class="box2">
        <img src="https://randomuser.me/api/portraits/women/13.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Developer 5</h3>
        <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
        </div> 
      </div>           
      <div class="box2">

      </div>     
  </div>

  </div>          
</section>
        
{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      <!--Import the Bootstrap CSS file:-->
      <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      />

      <!-- Matjax -->
      <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
      <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      
      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}
        
    </head>
    <body>
        <section class="section_carbon_app_navbar">
          <div class="container">
            <div class="carbon_app_navbar">
              <h1 class="logo">
                <span class="text-logo"><i class="fa-solid fa-leaf"></i> Carbon</span> App
              </h1>
              <nav>
                <ul>
                    <li>
                      <a href="{{url_for('users.register')}}">Register</a>
                    </li>
                    <li>
                      <a href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li>
                        <a href="{{url_for('home.home_home')}}">Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}">Methology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}">Carbon App</a>
                    </li>
                </ul>
              </nav> 
            </div>
          </div>
        </section>

        {% block content %} {% endblock %}

        <section class="section_footer">
          <div class="container">
            <div class="footer">
              <h1>
                Carbon App 
                <a href="#">
                  <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
                </a>
              </h1>
            </div>
          </div>
        </section>

        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>

capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_methodology">
    <div class="container">
  
      <div class="header">
        <div class="box"> 
          <h1 style="font-size:55px;"><span class="text-logo"> Methodology</span></h1>
          <p style="text-align:left;">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
          </p>
          <div class="container_buttons_links_header">
            <div class="btn">
                <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Paper</a>
            </div>
            <div class="btn">
                <a href="{{url_for('carbon_app.carbon_app_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Carbon App</a>
            </div>
          </div>  
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/methodology1.svg')}}"
            width="325" 
            height="325"
            alt=""/>
        </div>
      </div>
      
    </div>
</section> 

<!-- Methodology -->
<section class="section_body_methodology">
    <div class="container">
  
        <div class="methodology" style="display:block;">
            <h1 style="text-align:center;"> Methodology</h1>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
            </p>      
        </div>

        <div class="methodology" style="display:block;">
            <h1 style="text-align:center;"> Our numbers and formulas</h1>
            <p>
              We are going to studty some \(\LaTeX ~ formulas\) that could be useful for our project:
            </p> 
        </div>

        <!--Enumerated list (table with two columns)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:200px;">
                <ol start="1">
                    <li>
                        <h4>Mathematical expressions 1</h4>
                        <p class="text-left">
                            Mathematical expressions \( x = {-b \pm \sqrt{b^2-4ac} \over 2a} \) inside text.
                            <br>
                            Mathematical expressions outside text:
                            \[ x = {-b \pm \sqrt{b^2-4ac} \over 2a} \]
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table2" style="height:200px;">
                <ol start="2">
                    <li>
                        <h4>Mathematical expressions 2</h4>
                        <p class="text-left">
                            Mathematical expressions \( x^2 + y^2 = z^2 \) inside text.
                            <br>
                            Mathematical expressions outside text:
                            \[ x^2 + y^2 = z^2 \]
                        </p>
                    </li>
                </ol>
            </div>  
        </div>

        <!--Enumerated list (table with two columns)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:425px;">
                <ol start="3">
                    <li>
                        <h4>Sums</h4>
                        <p class="text-left">
                            Sum \(\sum_{n=1}^{\infty} 2^{-n} = 1\) inside text.
                            <br>
                            Sum outside text:
                            \[ \sum_{n=1}^{\infty} 2^{-n} = 1 \]
                        </p>
                    </li>
                    <li>
                        <h4>Products</h4>
                        <p class="text-left">
                            Product \(\prod_{i=a}^{b} f(i)\) inside text.
                            <br>
                            Product outside text:
                            \[ \prod_{i=a}^{b} f(i) \]
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table2" style="height:425px;">
                <ol start="5">
                    <li>
                        <h4>Limits</h4>
                        <p class="text-left">
                            Limit \(\lim_{x\to\infty} f(x)\) inside text.
                            <br>
                            Limit outside text:
                            \[ \lim_{x\to\infty} f(x) \]
                        </p>
                    </li>
                    <li>
                        <h4>Integrals</h4>
                        <p class="text-left">
                            Integral \(\int_{a}^{b} x^2 \,dx\) inside text.
                            <br>
                            Integral outside text:
                            \[ \int_{a}^{b} x^2 \,dx \]
                        </p>
                    </li>
                </ol>
            </div>  
        </div>

        

        <!--Enumerated list (table with one column)-->
        <div class="methodology">              
            <div class="box_table1">
                      
            </div>
            <div class="box_table1">
                <ol>
                    <li>
                        <h4>Buses</h4>
                        <p class="text-left">
                            The <strong>carbon dioxide emissions</strong> produced by buses are organized in <strong>four categories</strong>. The carbon dioxide emission produced by diesel buses is 0.10231 grammes per kilometer. The carbon dioxide emission produced by CNG buses is 0.08 grammes per kilometer. The carbon dioxide emission produced by petrol buses is 0.10231 grammes per kilometer. If the buses do not use fossil fuel, their dioxide carbon emissions are 0 grammes per kilometer.
                            <br>
                            To work out buses dioxide emissions, we use the next formula:
                            \[CO^2 = {Cte + \sqrt{f(km)} \over t}.\]
                            <br>
                            Where:
                            <ul style="text-align:left;">
                                <li>
                                    \(Cte\) is a constant, since the engine requires some fuel to initialize.
                                </li>
                                <li>
                                    \(km\) are the kilometers.
                                </li>
                                <li>
                                    \(f\) is a coefficient depending on the type of fuel (see paragraph above).
                                </li>
                                <li>
                                    \(t\) is the temperature, since in winter the engines require less fuel.
                                </li>
                            </ul>
                            
                        </p>
                    </li>
                    <li>
                        <h4>Cars</h4>
                        <p class="text-left">
                            ...
                        </p>
                    </li>
                    <li>
                        <h4>Planes</h4>
                        <p class="text-left">
                            ...
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table1">
                      
            </div>  
        </div>

        
      
    </div>
</section>

{% endblock content %}

capp/templates/users/login.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">

    <h1>Please, login here!</h1>
    <h4>Hello {{name}}, you can start to use the carbon app.</h4>

  </div>
</section> 

        
{% endblock content %}

capp/templates/users/register.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">

    <h1>Please, register here!</h1>

  </div>
</section> 

        
{% endblock content %}